### PR TITLE
Fix Waiting before exiting in #78

### PR DESCRIPTION
**Pull request by RaSan147**
The eventloop is not closed and waits a second on every call (idk the reason)

### CODE REVIEW

**Comment by RaSan147** [comment]
if its approved, kindly make a wrapper function of the even loop open+run+close and apply them in examples too

**Comment by rany2** [comment]
Could you refactor this into something like:

```py
loop = asyncio.get_event_loop()
try:
       loop.run_until...
finally:
       loop.close()
```

**Comment by rany2** [comment]
I wasn't aware that closing the event loop was important and caused this behavior, I assumed it was implicitly closed on exit. Thanks for noticing

**Comment by rany2** [comment]
Also please can you update the examples in this PR?

**Comment by rany2** [comment]
Thank you for your contribution!

**Comment by rany2** [comment]
FYI I can't see this behavior on Linux, so I'm presuming it's Windows only?

**Comment by RaSan147** [comment]
> FYI I can't see this behavior on Linux, so I'm presuming it's Windows only?

Probably yes (extremely sorry, i was busy a bit... So couldn't reply or do anything) I'll try to make a wrapper and update examples. Thanks

**Comment by RaSan147** [comment]
It seems you've already done it. Again sorry.
This tool is the best (was pulling my hair to generate voice in any potato hardware)

**Pull request merged**
