### PR TITLE
Fix False-Positive By Crappy AV Caused by GPL License File

### PR DESCRIPTION
**Pull request by Dobrowit**
I removed the blank line from the end of the file. This procedure is to change the checksum of the file so that it is not recognized as "Trojan.U.NjRat.tr" by GridinSoft and VirusTotal. The change does not change the content of the license but removes the problem when distributing software that contains edge_tts.

### CODE REVIEW

**Comment by Dobrowit** [comment]
You can check out how GridinSoft's junk product works:
https://gridinsoft.com/online-virus-scanner/id/3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986

I wonder how such a common file as a GPL license can be recognized as malicious code. Maybe someone from this company is malicious or stupid.

...VirusTotal also shows bad stuff when it finds a file with a license somewhere but it is a derivative of GridinSoft.

**Comment by rany2** [comment]
Your patch is empty: https://patch-diff.githubusercontent.com/raw/rany2/edge-tts/pull/170.patch

**Comment by Dobrowit** [comment]
I'm sorry but I don't grasp how exactly the GIT works :-) ...I guess I need to read the manual. :-)

**Comment by Dobrowit** [comment]
Now it's good :-) I learned something.
https://github.com/Dobrowit/edge-tts/commit/ab718e9063a14db4978ad06544faafb57d26ec17

**Comment by rany2** [comment]
I'll just end up distributing a markdown version instead.

**Pull request closed without merging**
