### PR TITLE
Fix 403 error related to Sec-MS-GEC and Sec-MS-GEC-Version parameters

### PR DESCRIPTION
**Pull request by BG5T**
Fixed a 403 Forbidden error related to authorization and added optional parameters Sec-MS-GEC and Sec-MS-GEC-Version.
- Sec-MS-GEC: Optional parameter for authentication.
- Sec-MS-GEC-Version: Optional parameter to specify the version for validation.

### CODE REVIEW

**Comment by rany2** [comment]
How does the API work? Is it manually updated by you or did you crack the algorithm?

**Comment by jianchang512** [comment]
> I Created an online API for distributing Sec-MS-GEC tokens for emergency use.我创建了一个在线 API，用于分发 Sec-MS-GEC 令牌以供紧急使用。
> 
> * GET request to retrieve the latest Sec-MS-GEC token.GET 请求检索最新的 Sec-MS-GEC 令牌。
> * API endpoint: https://edge-sec.myaitool.top/?key=edgeAPI 端点：https://edge-sec.myaitool.top/?key=edge
> * After obtaining the token, pass it as a parameter into the communicate function.获取 Token 后，将其作为参数传入 communicate 函数中。

Thank you for your work, can you please tell me if this api address is stable and available to the public, or is it possible to terminate the service at any time?

**Comment by rany2** [comment]
This solution is clunky but it could work. I'd rather it works out of the box without needing to manually set a token or relying on a web service other than Microsoft's.

**Comment by rany2** [comment]
Closing, I rather the token be derived by the program (i.e., it doesn't rely on third party API service).

**Pull request closed without merging**
