### PR TITLE
add the needed "MPV" dependency to requirements

### PR DESCRIPTION
**Pull request by YellowRoseCx**

### CODE REVIEW

**Comment by rany2** [comment]
It's not a Python dependency though.

**Comment by rany2** [comment]
If you could update the error message returned by edge-playback to be more informative as to how to install mpv on the platform the user is running on. That would help reduce the # of bug reports.

**Comment by YellowRoseCx** [comment]
> If you could update the error message returned by edge-playback to be more informative as to how to install mpv on the platform the user is running on. That would help reduce the # of bug reports.

Okay I could look into doing that




> It's not a Python dependency though.

It doesn't use/need the python-mpv binding package? I know you also need the executable but I thought it needed this too https://pypi.org/project/python-mpv/

**Comment by rany2** [comment]
It doesn't whatsoever. It just calls the MPV executable after the media and subtitles file is generated.

**Pull request closed without merging**
